// GENERATED CODE - DO NOT MODIFY BY HAND

// This file is generated by Hive's code generator.
// It links to the part directive in 'notes_model.dart'.
part of 'notes_model.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

// Adapter class for serializing and deserializing the NotesModel object.
class NotesModelAdapter extends TypeAdapter<NotesModel> {
  @override
  final int typeId = 0; // Unique identifier for this adapter.

  // Method to read data and convert it into a NotesModel object.
  @override
  NotesModel read(BinaryReader reader) {
    // Read the number of fields in the serialized object.
    final numOfFields = reader.readByte();
    // Read the fields into a map where keys are field IDs and values are field data.
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    // Return a new NotesModel object initialized with the read data.
    return NotesModel(
      title: fields[0] as String,
      description: fields[1] as String,
    );
  }

  // Method to write a NotesModel object to binary data.
  @override
  void write(BinaryWriter writer, NotesModel obj) {
    writer
      ..writeByte(2) // Number of fields being written.
      ..writeByte(0) // Field ID for the 'title'.
      ..write(obj.title) // Write the 'title' field.
      ..writeByte(1) // Field ID for the 'description'.
      ..write(obj.description); // Write the 'description' field.
  }

  // Override hashCode to ensure unique identification for this adapter.
  @override
  int get hashCode => typeId.hashCode;

  // Override equality operator to compare adapter instances by typeId.
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotesModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
